# Generated by Django 4.1.2 on 2022-12-10 15:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guser', '0003_guser_otp_active_alter_guser_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='bid_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.BigIntegerField()),
                ('status', models.CharField(choices=[('Highest', 'Highest'), ('Won', 'Won'), ('bid', 'bid')], default='bid', max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('bidUser', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Guser.guser')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='categories_image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('base_price', models.BigIntegerField()),
                ('buying_price', models.BigIntegerField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Under Review', 'Under Review'), ('Reject', 'Reject'), ('Conditional', 'Conditional')], default='Under Review', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(null=True)),
                ('G_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_item', to='Guser.guser')),
                ('bid_user', models.ManyToManyField(through='Item.bid_item', to='Guser.guser')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Item.category')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='item_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item_image/item_gallery/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Item.item')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.AddField(
            model_name='bid_item',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Item.item'),
        ),
    ]
