# Generated by Django 4.1.2 on 2022-12-15 21:34

import Item.models
import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from=['productName', 'id', 'start_date'], slugify=Item.models.custom_slugify, unique_with=['id']),
        ),
        migrations.AlterField(
            model_name='item',
            name='modified_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('UpComing', 'UpComing'), ('Under Review', 'Under Review'), ('Reject', 'Reject'), ('Conditional', 'Conditional'), ('Completed', 'Completed')], default='Under Review', max_length=20),
        ),
    ]
