# Generated by Django 4.1.2 on 2022-12-22 14:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0006_alter_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='productName',
            field=models.CharField(max_length=400),
        ),
    ]
