# Generated by Django 4.0 on 2023-05-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0008_alter_item_bid_user_alter_item_modified_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidsecurity',
            name='number',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bidsecurity',
            name='reference_number',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bidsecurity',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=20),
        ),
    ]
