# Generated by Django 4.1.2 on 2022-11-03 14:40

import Guser.models
import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guser',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='user__username', slugify=Guser.models.custom_slugify, unique_with=['user__username', 'phoneNumber']),
        ),
    ]
