# Generated by Django 4.1.2 on 2022-11-03 16:09

import Guser.models
import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guser', '0002_guser_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='guser',
            name='otp_active',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='guser',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='phoneNumber', slugify=Guser.models.custom_slugify, unique_with=['phoneNumber']),
        ),
    ]
