# Generated by Django 4.1.2 on 2022-12-15 23:05

import Guser.models
import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guser', '0008_alter_guser_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guser',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='phoneNumber', slugify=Guser.models.custom_slugify, unique_with=['phoneNumber']),
        ),
    ]
