# Generated by Django 4.0 on 2023-05-15 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Guser', '0009_alter_guser_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guser_user', to='auth.user'),
        ),
    ]
